### ISSUE TITLE
Include package score in public api

### ISSUE THREAD

**Issue by GroovinChip** [dart-lang/pub-dev#2326]
The public api returns JSON that includes basic package info like the package name, the author, etc. Please include the package score in that JSON response.

**Comment by jonasfj** [comment]
What is the use case for this?

I think at this point we're not quite ready to commit to a stable public API. Don't get me wrong, I'm sure you have awesome use cases, and we would be excited to enable them :) hehe

Note: I think the scores are available in some API but calling those APIs public or stable would be a far stretch, just be prepared that they may change. @isoos what's the end-point for checking score?

**Comment by isoos** [comment]
@GroovinChip: you can check the score here: `/api/packages/[pkg_name]/metrics` [(example)](https://pub.dev/api/packages/pana/metrics?pretty).

Please let us know your use case, as we are going to refactor parts of our API to be able to commit to long-term stability, and this is one of the suspects that would likely change.

**Comment by GroovinChip** [comment]
My use case is that I'm building a Flutter app that's basically a package explorer. I'd like to be able to retrieve as much information as possible :)

**Comment by GroovinChip** [comment]
While we're talking, why is it that when I do a call to `https://pub.dev/api/packages?sort=top` I don't get the packages sorted by score? On the website, if I select "overall score" from the dropdown, the web address shows as `https://pub.dev/packages?sort=top` and returns packages sorted by score. But the api call returns different results. Am I calling it incorrectly?

**Comment by jonasfj** [comment]
> My use case is that I'm building a Flutter app that's basically a package explorer.

Cool, that's super awesome :)

For what you're trying to do we simply do not have any stable API. Any end-points we have may change without notice or warning, at anytime... I hope we'll someday be able to offer more stable APIs.

The best documentation for these is the code:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/frontend/handlers/custom_api.dart

As you can see these don't have all the same query parameters.. but there is some cool stuff like `/api/packages?list=compact` which returns a list of all package names. and `/api/packages/<package>/metrics` which exposes scores...

**WARNING**: These things **will break** without warning or notice. These are internal APIs, not intended for external consumers. We will break them!

^ I'm repeating this, a lot to set your expectations accordingly. These APIs are not designed in a manner that they were intended to be used by others. They just are, and eventually they will go away or change.

**Comment by GroovinChip** [comment]
I see, thanks very much for going into detail. I'm glad you think the
project is cool!

Completely understandable regarding the apis breaking. Do you have any idea
when they might stabilize? Also, perhaps we can work together to build an
official pub Flutter app? Besides for being a package explorer, I wanted to
build in a favorites feature where users could easily access their favorite
packages, as well as get notifications when a new version is published.

**Comment by isoos** [comment]
@GroovinChip: after #2321 lands, you can check the changes on the `app/lib/frontend/handlers/routes.dart` file, we will try to user that as the main/single entry point for all the API and endpoint we support, and a new API version will manifest there eventually.

**Comment by GroovinChip** [comment]
Sounds good, thank you!

**Comment by jonasfj** [comment]
Some of the work I think is blocking API stabilization:
  - [ ] Finish [pub server specification](https://github.com/dart-lang/pub/blob/ecd5b413271f2699f8cd9e23aa4eebb5030c964f/doc/repository-spec-v2.md)
 - [ ] Support authentication for 3rd party servers (https://github.com/dart-lang/pub/issues/1381)
 - [ ] Support search query language (https://github.com/dart-lang/pub-dev/issues/1752)
 - [x] Switch to a decent routing library (https://github.com/dart-lang/pub-dev/pull/2321, almost landed)
 - [ ] Input/output validation against JSON schemas for APIs (https://github.com/dart-lang/pub-dev/issues/2142)

Before we get to there we probably need a proper JSON schema validator in Dart. If you're interested in contributing to the pub-dev server we can probably find some opportunities (with standalone integration tests this increasingly feasible).

I doubt we would be looking to build an app for pub.dev, but if users find it useful we don't have a problem recommending high quality community projects. That said I'm not sure a app is particularly useful. I think it's more important to improve the web interface on mobile, for example: improving generated documentation.

**Comment by isoos** [comment]
Score is exposed in the API, eg. https://pub.dev/api/packages/http/score
