### ISSUE TITLE
Tracking the status of the new UI

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dev#3246]
- [x] Header
  - [ ] mobile view's profile needs different format
  - [ ] mobile view's logout needs to be at the end of the "my ..." section
  - [ ] mobile view has no folding for "Flutter" and "Web & Server"
- [x] Search banner
  - [x] listing page on mobile requires a drawer icon
- [x] Landing page
  - [ ] square background does not have "semi-random" empty spaces like 
  - [ ] images do not go behind package cards
  - [x] weird page layout at some resolutions (some elements may be too large, some wrap weirdly)
  - [ ] featured packages not done yet (but should be easy to do if needed)
- [x] Listing page
  - [x] missing: mobile view hides platforms/runtimes by default
  - [x] missing: mobile view trigger
  - [x] missing: advanced controls (e.g. legacy)
  - [ ] mobile view trigger's inactive state is not from the design (needs white internal bars)
  - [ ] sort control has a simple down arrow instead of the styled one
  - [ ] publisher icon is shield instead of the geared checkmark
  - [x] tags are not styled yet
  - [ ] there is no badge for 'new' (< 30 days old) packages
  - [ ] API results are always shown, not hidden/toggled
- [x] Generic detail pages
  - [x] admin tabs are not styled with padlocks
  - [x] missing wrapper styles for mobile-view info-box
  - [x] icons inside the info-box should be lighter
  - [x] like button is not the icon from the design
  - [x] like block is misaligned
- [x] Package page
  - [ ] icon for experimental platforms #3384
  - [x] Versions tab
    - [ ] documentation icon is still the old one
    - [ ] download icon is still the old one
    - [ ] need to update JS code to switch to a different icon when documentation has failed
    - [x] tab content header style was not updated yet
- [x] Publisher page
  - [x] Admin tab
    - [ ] Input fields have their label inside / on the border, and not outside. Should we use that? (should be consistent with other places, e.g. create publisher)
    - [ ] "Invite member" flow has many extra text currently, new design does not have it. Should we display that as part of the confirm?
    - [x] "Remove member" button is unstyled and non-material (no ripple).
- [x] Help page
- [x] Footer

**Comment by isoos** [comment]
Pending issues were discussed in the last design review meeting, closing this.
