### ISSUE TITLE
meta: Launch with happiness survey

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4386]
The following tasks is blocking launch with happiness survey:

 * [x] Migrate to Google Tag Manager (currently behind experimental)
 * [x] Remove HaTS from Google Tag Manager
 * [x] Add HaTS to Google Tag Manager (after deployment)
 * [x] Refactor `History` entities
   * Add `AuditLogRecord` with properties: `created`, `expires`, `kind`, `agent`,
     `summary`, `reason`, `users`, `packages`, `packageVersions`, `publishers`.
   * Expire `AuditLogRecord` entities after 60 days
   * Retain `AuditLogRecord` for `package-published` events indefinitely.
 * [x] Enabled administration of uploaders through the package admin page.
 * [x] Error page requiring a login before login when accepting an invitation should
   * say: "if you have no signed-in on pub.dev before a pub.dev profile will automatically be created upon sign-in"
   * in-line with [mockup](https://user-images.githubusercontent.com/149732/103291967-2282b400-49ed-11eb-85dd-dd8e81b278b3.png)

 * [x] Publisher creation page should state what a publisher can do ([mockup](https://user-images.githubusercontent.com/149732/103292005-3af2ce80-49ed-11eb-8f53-f734a3bf7c2b.png))

**Comment by jonasfj** [comment]
Deployed today.
