### ISSUE TITLE
The markdown `todo` is not rendered correctly.

### ISSUE THREAD

**Issue by hyochan** [dart-lang/pub-dev#6200]
The markdown `todo` isn't rendered correctly.
- [ ] <=== Hope this renders correctly.

## Current
<img width="400" alt="Screenshot 2022-11-20 at 1 41 53 PM" src="https://user-images.githubusercontent.com/27461460/202885969-147fe8ac-750c-4a4a-bb32-d8796374cf3d.png">

## Expected as Github readme
<img width="400" alt="Screenshot 2022-11-20 at 1 42 06 PM" src="https://user-images.githubusercontent.com/27461460/202885976-1f71ed51-eab8-4b72-b5df-9ac093542511.png">

**Comment by isoos** [comment]
This seems to be a bug on pub-dev, as running markdown on the input renders the correct HTML:
```
dart pub run markdown --extension-set GitHubWeb
Deprecated. Use `dart run` instead.
## TODO

- [x] Support optional `horizontal` mode
- [x] Separator support in `ListView`
<h2 id="todo">TODO</h2>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" checked="true"></input>Support optional <code>horizontal</code> mode</li>
<li class="task-list-item"><input type="checkbox" checked="true"></input>Separator support in <code>ListView</code></li>
</ul>
```

**Comment by hyochan** [comment]
> This seems to be a bug on pub-dev, as running markdown on the input renders the correct HTML:
> 
> ```
> dart pub run markdown --extension-set GitHubWeb
> Deprecated. Use `dart run` instead.
> ## TODO
> 
> - [x] Support optional `horizontal` mode
> - [x] Separator support in `ListView`
> <h2 id="todo">TODO</h2>
> <ul class="contains-task-list">
> <li class="task-list-item"><input type="checkbox" checked="true"></input>Support optional <code>horizontal</code> mode</li>
> <li class="task-list-item"><input type="checkbox" checked="true"></input>Separator support in <code>ListView</code></li>
> </ul>
> ```

So is there anything I can do to fix this? I am not getting your solution.

**Comment by isoos** [comment]
> So is there anything I can do to fix this? I am not getting your solution.

No action is needed on your part. I've tagged the issue as bug, and hopefully we'll have some time to look into it why it happens and fix it.

**Comment by hyochan** [comment]
@isoos Thanks! Sounds great and looking forward to it 👀

**Comment by isoos** [comment]
@jonasfj: This seems to be caused by the HTML sanitization of the markdown code. We could either allow `input` in `package:sanitize_html`, or rewrite the `<input>` element (and maybe related styles) to `<span>` elements and/or unicode characters. wdyt?

**Comment by jonasfj** [comment]
They are rendered as `input` on github because you actually can modify them.

Although they are rendered as disabled input when not signed in...

------------------------------

Hmm, I guess:
https://github.com/gjtorikian/html-pipeline/blob/main/lib/html/pipeline/sanitization_filter.rb

which is the basis for sanitize_html is outdated.

We might need to take a look at refactoring sanitize_html to allow more, and be more flexible.

**Comment by isoos** [comment]
> We might need to take a look at refactoring sanitize_html to allow more, and be more flexible.

I don't mind keeping it strict, however, if we don't change sanitize_html, then we should convert the inputs to unicode characters instead. Which way do you prefer?

**Comment by jonasfj** [comment]
won't unicode break in some browsers / cases....?

**Comment by isoos** [comment]
> won't unicode break in some browsers / cases....?

IIRC it depends on the font face and the system fonts available. An alternative would be to use just an SVG icon as a replacement, e.g. 
<img width="185" alt="image" src="https://user-images.githubusercontent.com/4778111/203130563-ab860223-58f8-4a17-b27f-5446a18e5dbc.png">

**Comment by jonasfj** [comment]
In that case I propose that we use `<input type="checkbox" disabled>` maybe we patch `package:markdown` to create disabled checkboxes?

**Comment by jonasfj** [comment]
SVG would also be nice, but how can we reduce the number of hacks?

Can we pass parameters to `package:markdown` that changes how it renders [OrderedListWithCheckboxSyntax](https://pub.dev/documentation/markdown/latest/markdown/OrderedListWithCheckboxSyntax-class.html) ?

I guess we could subclass `OrderedListWithCheckboxSyntax`? and change the output it returns..

**Comment by isoos** [comment]
> Can we pass parameters to package:markdown that changes how it renders OrderedListWithCheckboxSyntax ?

Unfortunately, it looks like, changing the `package:markdown` rendering is not easy:
https://github.com/dart-lang/markdown/blob/master/lib/src/block_syntaxes/list_syntax.dart#L57-L237

> In that case I propose that we use <input type="checkbox" disabled> maybe we patch package:markdown to create disabled checkboxes?

We'd need to both change the markdown output to use `disabled` and also change `package:sanitize_html` to not remove the `input` tag and its attributes. I'd rather prefer this one than just changing it into an icon (that we need to distribute).
