### ISSUE TITLE
Tracking completion widget issues

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dev#8189]
- [ ] fixing absolute positioning bug
- [ ] style change: blend with input field background
- [ ] style change: padding + rounded corners in the bottom
- [ ] style change: already typed text with different color
- [ ] display it in mini search widget (e.g. on package page)
- [ ] include the prefix in the result list
- [ ] `#` as a shortcut for `topic:` completion (also in query canonicalization)
